; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:rp2040_purple]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico ; O usa 'waveshare_rp2040_zero' si el factor de forma coincide
framework = arduino
board_build.core = earlephilhower ; Recomendado para máxima compatibilidad
monitor_speed = 115200
build_flags = 
    -I"${platformio.packages_dir}/framework-arduinopico/pico-sdk/src/rp2/pico_stdio/include"
    -DSDK_PICO_FREERTOS=1
    -DGPIO_COUNT=30