; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
; Memoria de cámara en PSRAM externa
board_build.arduino.memory_type = qio_opi

; Partición con más espacio para la app
board_upload.flash_size = 8MB
board_build.partitions = huge_app.csv

lib_deps =
    esp32-camera

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_ESP32S3_DEV
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1    ; ← Esta línea es clave para ver el Serial

monitor_speed = 115200
monitor_filters = esp32_exception_decoder