[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

# Copia esta línea completa (es un solo enlace):
lib_deps = https://github.com/micro-ROS/micro_ros_arduino.git#humble
# No olvides estas dos líneas para que sepa que es para Humble y Serial:
board_microros_distro = humble
board_microros_transport = serial
build_flags =
    -L .pio/libdeps/esp32dev/micro_ros_arduino/src/esp32/
    -l microros

